// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxgogtenniyzjfzcwodn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Z29ndGVubml5empmemN3b2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjU1MzgsImV4cCI6MjA2MzYwMTUzOH0.YENTTFp9Wt7BCQ9QN66wxHYhmiGy-Fjz9uBrLIanhWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);